image: Visual Studio 2019
install:
  - SET PATH=C:\Ruby%RUBYVER%\bin;%PATH%
  - ridk version
build: off
test_script:
  - ruby print_enc.rb abc √§√∂√º–ñ„ÅÇùÑû
environment:
  matrix:
    - RUBYVER: 30-x64
    - RUBYVER: 27-x64
    - RUBYVER: 25
